# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(default='no-image.png', upload_to='book_pictures/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='no-image.png', upload_to='profile_pictures/'),
        ),
    ]
